FROM node:20-alpine

WORKDIR /app

# deps primeiro (cache)
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# código entra via volume
EXPOSE 3001

CMD ["pnpm", "start:dev", "auth-service"]
